services:
  - type: web
    name: ufc-activities-mpa
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn ufc_activities_django.wsgi:application
